// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4CmQA_PLvXGBbwZyygqDS0zFjkihi4fo',
    appId: '1:670991831540:web:3b04896c06f1d3967da9a1',
    messagingSenderId: '670991831540',
    projectId: 'grihalakshmi-financeplanner',
    authDomain: 'grihalakshmi-financeplanner.firebaseapp.com',
    storageBucket: 'grihalakshmi-financeplanner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmKCxXuQfspAJ3ewZ-dZ-CHvIr95T7V_g',
    appId: '1:670991831540:android:d16ce73edcf282877da9a1',
    messagingSenderId: '670991831540',
    projectId: 'grihalakshmi-financeplanner',
    storageBucket: 'grihalakshmi-financeplanner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuwLit6kidvqbcb07aeZIOr72VU6HyVAg',
    appId: '1:670991831540:ios:22005af9fca4a9667da9a1',
    messagingSenderId: '670991831540',
    projectId: 'grihalakshmi-financeplanner',
    storageBucket: 'grihalakshmi-financeplanner.firebasestorage.app',
    iosBundleId: 'com.devbose.grihalakshmi',
  );
}
